<?xml version="1.0"?>
<robot name="gears_smp" xmlns:xacro="http://www.ros.org/wiki/xacro">
<!--
    A rough model of the Gears SMP rover. Details at http://www.gearseds.com/surface_mobility_platform.html
-->
    <!-- Add relevant macros -->
    <xacro:include filename="$(find rover_robots)/urdf/macros/components/wheel.urdf.xacro" />
    <xacro:include filename="$(find rover_robots)/urdf/macros/components/rocker.urdf.xacro" />


    <xacro:property name="PI" value="3.1415926535897931" />

    <!-- All dimensions in SI units (kg, m, etc.)-->

    <!-- Chassis dimensions -->
    <xacro:property name="chassis_length" value=".30"/>
    <xacro:property name="chassis_width" value=".14"/>
    <xacro:property name="chassis_height" value=".0889"/>
    <xacro:property name="chassis_mass" value="1.584994"/>

    <!-- Rocker dimensions and positioning -->
    <xacro:property name="rocker_length" value=".2667"/>
    <xacro:property name="rocker_width" value=".03175"/>
    <xacro:property name="rocker_height" value=".03175"/>
    <xacro:property name="rocker_mass" value="1.387336"/>

    <xacro:property name="rocker_x" value="0.0"/>
    <xacro:property name="rocker_y" value="${0.12065-0.5*rocker_width}"/>
    <xacro:property name="rocker_z" value="0.090242"/>

    <!-- Wheel dimensions -->
    <xacro:property name="wheel_radius" value="0.08255"/>
    <xacro:property name="wheel_depth" value=".0508"/>
    <xacro:property name="wheel_mass" value="0.283642"/>

    <!-- Wheel positioning -->
    <xacro:property name="wheel_spacing_x" value="0.19678256"/>
    <xacro:property name="wheel_spacing_y" value="0.0381365"/>
    <xacro:property name="wheel_spacing_z" value="-0.05257042"/>

    <!-- Create base_link for central robot chassis -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${chassis_mass}"/>
            <inertia
                ixx="0.01042" ixy="0.001177" ixz="-0.0008871"
                iyy="0.01045" iyz="0.0002226"
                izz="0.01817"/>
            </inertial>
    </link>

    <!-- Add the rockers -->
    <xacro:rocker prefix="left" parent="base_link" rockerx="${rocker_length}" rockery="${rocker_width}" rockerz="${rocker_height}" rockerkg="${rocker_mass}" mimicing="0" mimic_joint="">
        <origin xyz="${rocker_x} ${rocker_y} ${-rocker_z}" rpy="0 0 0"/>
        <inertia
            ixx="0.002956" ixy="-0.000001489324" ixz="-0.000008103407"
            iyy="0.02924"  iyz="0.00007112"
            izz="0.02832"/>
    </xacro:rocker>

    <xacro:rocker prefix="right" parent="base_link" rockerx="${rocker_length}" rockery="${rocker_width}" rockerz="${rocker_height}" rockerkg="${rocker_mass}"  mimicing="1" mimic_joint="left_rocker_joint">
        <origin xyz="${rocker_x} ${-rocker_y} ${-rocker_z}" rpy="0 0 0"/>
        <inertia
            ixx="0.002956" ixy="-0.000001489324" ixz="-0.000008103407"
            iyy="0.02924"  iyz="0.00007112"
            izz="0.02832"/>
    </xacro:rocker>

    <!-- Add the wheels -->
    <xacro:wheel prefix="front_left" parent="left_rocker_link" wheelrad="${wheel_radius}" wheeldepth="${wheel_depth}" wheelkg="${wheel_mass}" >
        <origin xyz="${wheel_spacing_x} ${wheel_spacing_y} ${wheel_spacing_z}" rpy="0 0 0"/>
        <inertia
            ixx="0.000391"  ixy="0.00000123962" ixz="5.52582e-7"
            iyy="0.0004716" iyz="-0.000002082042"
            izz="0.000391"/>
    </xacro:wheel>

    <xacro:wheel prefix="rear_left" parent="left_rocker_link" wheelrad="${wheel_radius}" wheeldepth="${wheel_depth}" wheelkg="${wheel_mass}">
        <origin xyz="${-wheel_spacing_x} ${wheel_spacing_y} ${wheel_spacing_z}" rpy="0 0 0"/>
        <inertia
            ixx="0.000391"  ixy="0.00000123962" ixz="5.52582e-7"
            iyy="0.0004716" iyz="-0.000002082042"
            izz="0.000391"/>
    </xacro:wheel>

    <xacro:wheel prefix="front_right" parent="right_rocker_link" wheelrad="${wheel_radius}" wheeldepth="${wheel_depth}" wheelkg="${wheel_mass}">
        <origin xyz="${wheel_spacing_x} ${-wheel_spacing_y} ${wheel_spacing_z}" rpy="0 0 0"/>
        <inertia
            ixx="0.000391"  ixy="0.00000123962" ixz="5.52582e-7"
            iyy="0.0004716" iyz="-0.000002082042"
            izz="0.000391"/>
    </xacro:wheel>

    <xacro:wheel prefix="rear_right" parent="right_rocker_link" wheelrad="${wheel_radius}" wheeldepth="${wheel_depth}" wheelkg="${wheel_mass}">
        <origin xyz="${-wheel_spacing_x} ${-wheel_spacing_y} ${wheel_spacing_z}" rpy="0 0 0"/>
        <inertia
            ixx="0.000391"  ixy="0.00000123962" ixz="5.52582e-7"
            iyy="0.0004716" iyz="-0.000002082042"
            izz="0.000391"/>
    </xacro:wheel>

    <!-- Add the differential suspenion sim plugin and reference the two rockers, as well as the force constant between them -->
    <gazebo>
        <plugin name="rover_gazebo_diff_plugin" filename="librover_gazebo_diff_plugin.so">
            <jointA>left_rocker_joint</jointA>
            <jointB>right_rocker_joint</jointB>
            <forceConstant>100.0</forceConstant>
        </plugin>
    </gazebo>

        <!-- Load the Gazebo-ROS Control interface -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <!--<robotNamespace></robotNamespace>-->
        </plugin>
    </gazebo>


</robot>